### ISSUE TITLE
Cyclical network with skeleton on edges of image 

### ISSUE THREAD

**Issue by Lvulis** [jonschwenk/RivGraph#34]
This is an issue I've come across and solved, but good to know for debugging/figuring out why networks don't come out. Not sure of a smarter way to handle it automatically. 

Sometimes a cyclical channel skeleton that wraps around the edge of the image. This is primarily caused when using a watermask in a local geographic projection that has no data values on the edges. This arises typically when projecting rectangles from WGS84 (EPSG 4326) into a local UTM zone, e.g. with the global surface water masks. Here's an example of the visual offset and resulting skeleton (tealish is no data, blue is water, grey land, yellow is the shoreline, orange is skeleton even after pruning).

![image](https://user-images.githubusercontent.com/18738680/103107918-c4725d00-45f7-11eb-990f-c6b49bebeba9.png)

**Solution**
Define the subaerial extent of the delta as a line vector which'll be used as the argument of the shoreline in prune_network. This will clip out the weird skeleton outside the image. When doing this, the inlet node passed to prune network should have its nearest neighbor _within_ the subaerial delta to work. Example here:
![image](https://user-images.githubusercontent.com/18738680/103141467-77e75a00-46a9-11eb-8679-95813d54303d.png)

**Comment by jonschwenk** [comment]
Nice example, thanks for adding it! I will reference it in the docs.

The correct way to handle this is to explicitly set the nodata in the mask to 0. I.e., the mask should contain only 1s and 0s, with no nodata.

While your solution seems to work, I would caution against using it. This is because wherever your shoreline intersects the skeleton/links, an _outlet_ node will be created/assigned there. Obviously you don't want an outlet node at the apex of the delta. In practice, _RivGraph_ _might_ overwrite the apex outlet node as an inlet, but I'm not sure about it. The best approach is to just ensure you have a proper mask.

**Comment by Lvulis** [comment]
Jon,

Not sure if I'm on a very old version of RG but I don't seem to have that issue you raised.

**Comment by jonschwenk** [comment]
Are you sure? I just checked the code and it looks like an outlet node should be created where the shoreline intersects the apex link.

**Comment by Lvulis** [comment]
You're correct. I hadn't noticed that. When correctly ensuring there's no NA values, so no cyclical network, using the subaerial delta extent as the shoreline argument won't yield an outlet on the apex link.
