### ISSUE TITLE
Mask assumptions leading to 'multiple inlet nodes' 

### ISSUE THREAD

**Issue by Lvulis** [jonschwenk/RivGraph#52]
Ran into the following bug today on Delft3D data where the delta metrics failed due to "multiple inlets" but no sources/sinks were found in the directionality step. It was because there was a node disconnected from the rest of the network in the adjacency matrix due to a mask assumption. I'm attaching the data [here](https://drive.google.com/file/d/1mOgDnYzyR2g_sLFa5hl0QRpSM0PUCZEj/view?usp=sharing) as an example and will refer explicitly to the node/link ids here.

Here's the the code snippet below showing what happened. The explanation below details what caused this bug and what needs to be done. 
```path_results = delta_dir + "/RG_0.3/time_" + str(i)
path_mask = delta_dir + "/projected/network_" + str(i) + ".tif"

# Instantiate the delta class
delt = delta(name, path_mask, path_results, verbose=True)
delt.compute_network()
delt.to_geovectors('network', ftype = 'json')


path_shrln = os.path.join(delta_dir, "/shoreline/shoreline_" + str(i) + ".shp")
path_inlet = os.path.join(delta_dir, "inlet_nodes.shp")

path_shrln = delta_dir + "/shoreline/shoreline_" + str(i) + ".json"
path_inlet = delta_dir + "/inlet_nodes.shp"

delt.prune_network(path_shoreline=path_shrln, path_inletnodes=path_inlet)

delt.compute_link_width_and_length()
delt.assign_flow_directions()
# delt.links, delt.nodes = lnu.add_artificial_nodes(delt.links, delt.nodes, delt.gdobj)
delt.compute_link_width_and_length() # Need to re-compute because we've split some links into 2 in order to add artificial nodes.
delt.to_geovectors('network', ftype='json')

delt.plot('directions')

delt.to_geotiff('directions')

adj_w = delt.adjacency_matrix(weight='wid_adj') # Can also weight by 'len_adj' or provide a vector of your own weights.
# print(adj_w)

path_adj = path_results + "/w_adj.csv"

np.savetxt(path_adj, adj_w, delimiter=",")
delt.save_network()

nodes = delt.nodes
links = delt.links

delt.compute_topologic_metrics()
Resolving links and nodes...done.
Computing distance transform...done.
Computing link widths and lengths...done.
Using ~\W0.01T0.01_rep_fixlinks.csv to manually set flow directions.
The following cycles (links) were fixed, but should be manually checked: [[352, 328, 329, 339, 342, 349, 351]]
Computing link widths and lengths...done.
Geotiff written to ~\W0.01T0.01_rep_link_directions.tif.
Links and nodes saved to pickle file: ~\W0.01T0.01_rep_network.pkl.
Traceback (most recent call last):

  File "<ipython-input-153-0cda936bec9b>", line 39, in <module>
    delt.compute_topologic_metrics()

  File "C:\Anaconda3\envs\RG_0.3\lib\site-packages\rivgraph-0.3-py3.8.egg\rivgraph\classes.py", line 670, in compute_topologic_metrics
    self.topo_metrics = dm.compute_delta_metrics(self.links, self.nodes)

  File "C:\Anaconda3\envs\RG_0.3\lib\site-packages\rivgraph-0.3-py3.8.egg\rivgraph\deltas\delta_metrics.py", line 40, in compute_delta_metrics
    deltavars = intermediate_vars(G)

  File "C:\Anaconda3\envs\RG_0.3\lib\site-packages\rivgraph-0.3-py3.8.egg\rivgraph\deltas\delta_metrics.py", line 124, in intermediate_vars
    deltavars['apex'], deltavars['outlets'] = find_inlet_outlet_nodes(deltavars['A_w'])

  File "C:\Anaconda3\envs\RG_0.3\lib\site-packages\rivgraph-0.3-py3.8.egg\rivgraph\deltas\delta_metrics.py", line 221, in find_inlet_outlet_nodes
    raise RuntimeError('The graph contains more than one apex.')

RuntimeError: The graph contains more than one apex.
```
The inlet node id is 257 and is in the 90th row/col of the adjacency matrix (90th from zero-index). Node 176 (row/col 47) however has no incoming values in the adjacency matrix. It does have 3 links connected to it in the node/link representation, but there's one link (235) crossing a small (3 pixel) island that doesn't click into node for whatever reason. Not sure if this is because the graphiphy function (or the underlying functions) assume the directionality pixels are all water.

The directionality pixel was land because in the skeletonize_graph call in m2g, any holes (i.e. islands) that are 4 pixels or less are filled, that is no islands of 4 pixels or less are allowed in RG. This is a fine assumption, but (1) is it totally necessary? and (2) I was checking the docs and didn't see anything about it is posted! 

This bug also resulted in the nodes['inlet'] array becoming empty for some reason, not sure why. 

The mask issue can be fixed by putting something into the documents, or removing this assumption, what do you folks think is better? I can push something into the docs for the former. 

Additionally should some kind of error catcher be put into the dm.graphiphy to report if there's multiple inlet nodes? This would probably let the user know something is wrong. I can push something for this as well.

**Comment by Lvulis** [comment]
This issue has come up again in a different mask from the same set of data (Delft3D runs). Again, ran the same script above and the error of multiple inlet nodes popped up. I don't reattach the data because the error is essentially the same, but can if you're interested.

Making a note here that the error is that islands less than or equal to 4 pixels in a 4-neighbor sense should be removed, rather than islands in an 8-neighbor sense. A straggler island that was left in the mask ended up leaving a 4-pixel link that had width vector {0, 0, 50, 100}. The adj_w came out to be zero, so RG (and networkx) think there's no incoming flow.

**Comment by jonschwenk** [comment]
Impressive job here tracking this down. This is a known (only probably to me) issue that I was hoping would never cause a problem.

Indeed, RivGraph simplifies the skeleton by filling holes in the skeleton of 4 pixels or less. Is this strictly necessary? I'm not actually sure. The reason it exists is that without this step, converting from a skeleton to a set of links and nodes was failing. The real problem is upstream, somewhere in the mask_to_graph code. It is quite involved and I tried to fix it at the time of initial development, but this was the best solution I came up with.

In your case, it looks like this:
![image](https://user-images.githubusercontent.com/14874485/118341935-709cdd80-b4de-11eb-87a6-bbbc24fc8aec.png)

Clearly the node there is not inside the original mask--this is because that 2-pixel island gets filled in the skeleton simplification, which you have pointed out. This occurs in  mask_to_graph in both the [delta ](https://github.com/jonschwenk/RivGraph/blob/9672730dbe362ad9b5aab598e9fcc8e89a9a87e5/rivgraph/mask_to_graph.py#L311)and the [river ](https://github.com/jonschwenk/RivGraph/blob/9672730dbe362ad9b5aab598e9fcc8e89a9a87e5/rivgraph/mask_to_graph.py#L368) skeletonization functions. In your case, this filling combined with the short link resulted in a 'wid_adj' of 0 for that link, exactly as you described.

If you comment out those three lines (i.e. don't fill holes in the skeleton), you get what you expect:
![image](https://user-images.githubusercontent.com/14874485/118342093-236d3b80-b4df-11eb-81b1-ec032d841e0e.png)

and the error you describe no longer exists.

**Solution**
I am not comfortable commenting out those lines without more extensive testing on other masks. The filling exists for a reason, and unfortunately I did not document it well enough at the time to recall exactly what it is. I therefore propose two workarounds:

1. Comment the lines out yourself. (We could also think about letting the user specify this).
2. Upsample your mask (i.e. increase the resolution). This will make that island greater than 4 pixels and you will no longer have the issue. Increases runtime significantly though (although your masks are small enough that this won't matter).

There is another way to "fix" the issue that I'm also not keen on: changing the algorithm that computes 'wid_adj' to not accept 0 as a width. This is hacky, though, and is yet another band-aid for the real problem.

In the meantime, I agree that this should be laid out in the documentation more explicitly. @Lvulis can you suggest a good place to do it?

Also, I added a warning that will alert a user when running compute_delta_metrics() if any of their weights are zero or negative. This will hopefully make the debugging process less painful in the future.

**Comment by jonschwenk** [comment]
The documentation for this issue has now been created: https://jonschwenk.github.io/RivGraph/issues/index.html

Leaving it open as the source of the issue still remains.
